version: "3.8"

networks:
  orgscale-network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: orgscale-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - orgscale-mongo-data:/data/db
    networks:
      - orgscale-network

  redis:
    image: redis:alpine
    container_name: orgscale-redis
    ports:
      - "6379:6379"
    environment:
      #   - REDIS_PORT=6379
      #   - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - orgscale-redis-data:/data
    networks:
      - orgscale-network

  app:
    build: .
    container_name: orgscale-app-server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: 3000
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_URI: "mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      API_KEY: ${API_KEY}
    depends_on:
      - mongo
      - redis
    networks:
      - orgscale-network

volumes:
  orgscale-mongo-data:
  orgscale-redis-data:
